services:
  harmonia:
    image: ghcr.io/teajhay/harmonia-docker:main
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "2223:22"
    env_file:
      - stack.env
    volumes:
      - nix-store:/nix
      - harmonia-keys:/keys
volumes:
  nix-store:
  harmonia-keys:
